spring.application.name=EnviosApi
server.port=8081

# Conexion a Base de Datos MariaDB
spring.datasource.url=jdbc:mariadb://localhost:3306/olva_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

# Configuracion de Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configuracion de BonitaSoft
bonita.api.url=http://localhost:8080/bonita
bonita.api.username=william.jobs
bonita.api.password=bpm
bonita.api.process.name=OLVA_Clasificacion_Carga
