<?xml version="1.0" encoding="UTF-8"?>
<xmi:XMI xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:connectorconfiguration="http://www.bonitasoft.org/model/connector/configuration" xmlns:decision="http://www.bonitasoft.org/ns/bpm/process/decision" xmlns:expression="http://www.bonitasoft.org/ns/bpm/expression" xmlns:notation="http://www.eclipse.org/gmf/runtime/1.0.3/notation" xmlns:process="http://www.bonitasoft.org/ns/bpm/process">
  <process:MainProcess xmi:id="_nKx3EG1HEfGFvIBFhOqB5w" name="customer-service" bonitaModelVersion="9">
    <elements xmi:type="process:Pool" xmi:id="_nKx3EW1HEfGFvIBFhOqB5w" name="Proceso de Gestión de Reclamos">
      <elements xmi:type="process:Lane" xmi:id="_nKx3Em1HEfGFvIBFhOqB5w" name="Cliente" actor="_P_qhsG1PEfGFvIBFhOqB5w">
        <elements xmi:type="process:StartEvent" xmi:id="_nKx3E21HEfGFvIBFhOqB5w" name="Inicio de Reclamo" outgoing="_2zc4gG8dEfGgjsG-ztl8Nw">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_nKx3FG1HEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_nKx3FW1HEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_nKx3Fm1HEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_uZpRgG1HEfGFvIBFhOqB5w" name="Atención al Cliente (ATC)" actor="_DM1BAG1SEfGFvIBFhOqB5w">
        <elements xmi:type="process:Task" xmi:id="_zLk6AG1IEfGFvIBFhOqB5w" documentation="Regla: Verificar si el paquete contiene material prohibido o mal embalaje (bolsas negras)&#xD;&#xA;" name="Validar Requisitos Iniciales" outgoing="_1CR89G1IEfGFvIBFhOqB5w" incoming="_2zc4gG8dEfGgjsG-ztl8Nw" actor="_DM1BAG1SEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_xsPOMm1IEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_xsPOMW1IEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_xsPOM21IEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_40Nc0m1QEfGFvIBFhOqB5w">
            <leftOperand xmi:type="expression:Expression" xmi:id="_40Nc021QEfGFvIBFhOqB5w" name="reclamoVar" content="reclamoVar" type="TYPE_VARIABLE" returnType="com.company.model.Reclamo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_40Nc1G1QEfGFvIBFhOqB5w" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_40Nc1W1QEfGFvIBFhOqB5w" name="reclamoVarInput.articuloProhibido" content="reclamoVarInput?.articuloProhibido" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_40Nc1m1QEfGFvIBFhOqB5w" name="reclamoVarInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_40Nc121QEfGFvIBFhOqB5w" type="JAVA_METHOD" expression="setArticuloProhibido">
              <inputTypes>java.lang.Boolean</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_xsPONG1IEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_xsPONW1IEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_xsPONm1IEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_xsPOOG1IEfGFvIBFhOqB5w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_xsPON21IEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_zLk6Cm1IEfGFvIBFhOqB5w">
            <targetForm xmi:type="expression:Expression" xmi:id="_9xkusG1QEfGFvIBFhOqB5w" name="validarRequisitosATC" content="02cad2c9-8dd9-46e6-a266-148e835231db" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_zLk6CW1IEfGFvIBFhOqB5w">
            <inputs xmi:type="process:ContractInput" xmi:id="_40Nc0G1QEfGFvIBFhOqB5w" name="reclamoVarInput" type="COMPLEX" dataReference="reclamoVar" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_40Nc0W1QEfGFvIBFhOqB5w" name="articuloProhibido" type="BOOLEAN" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_29AlMHVUEfGkzq9efzNXtg" expression="return reclamoVarInput.articuloProhibido != null" errorMessage="Debe confirmar si el paquete contenía un artículo prohibido." name="validarArticuloProhibido">
              <inputNames>reclamoVarInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_zLk6DG1IEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_1nkbUG1IEfGFvIBFhOqB5w" name="¿Pasa el filtro?" outgoing="_6wn_0G1IEfGFvIBFhOqB5w _BwQEYG1JEfGFvIBFhOqB5w" incoming="_1CR89G1IEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_1CRV4m1IEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_1CRV4W1IEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_1CRV421IEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_FJ2dcG1JEfGFvIBFhOqB5w" name="Fin1" incoming="_FJ3rkG1JEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FJ3EgW1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FJ3EgG1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FJ3Egm1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_i3ej8G1JEfGFvIBFhOqB5w" name="Fin2" incoming="_i3fLBG1JEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_i3ej8m1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_i3ej8W1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_i3ej821JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_1zH1YG9IEfGjyPnck1rwvA" name="Enviar correo de rechazo por Incumplimiento de Términos" outgoing="_FJ3rkG1JEfGFvIBFhOqB5w" incoming="_6wn_0G1IEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_6wnYwW1IEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_6wnYwG1IEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_6wnYwm1IEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_TOmesG1WEfGFvIBFhOqB5w" name="correoRechazoTerminos" definitionId="email" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_TOmesW1WEfGFvIBFhOqB5w" definitionId="email" version="1.3.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmesm1WEfGFvIBFhOqB5w" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_TOmes21WEfGFvIBFhOqB5w" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmetG1WEfGFvIBFhOqB5w" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_TOmetW1WEfGFvIBFhOqB5w" name="1025" content="1025" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmetm1WEfGFvIBFhOqB5w" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_TOmet21WEfGFvIBFhOqB5w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmeuG1WEfGFvIBFhOqB5w" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_TOmeuW1WEfGFvIBFhOqB5w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmeum1WEfGFvIBFhOqB5w" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_TOmeu21WEfGFvIBFhOqB5w" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmevG1WEfGFvIBFhOqB5w" key="authType">
                <expression xmi:type="expression:Expression" xmi:id="_TOmevW1WEfGFvIBFhOqB5w" name="Basic authentication" content="Basic authentication" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmevm1WEfGFvIBFhOqB5w" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_TOmev21WEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmewG1WEfGFvIBFhOqB5w" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_TOmewW1WEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmewm1WEfGFvIBFhOqB5w" key="oauth2AccessToken">
                <expression xmi:type="expression:Expression" xmi:id="_TOmew21WEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmexG1WEfGFvIBFhOqB5w" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_TOmexW1WEfGFvIBFhOqB5w" name="notificaciones@olvacourier.com" content="notificaciones@olvacourier.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmexm1WEfGFvIBFhOqB5w" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_TOmex21WEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmeyG1WEfGFvIBFhOqB5w" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_TOmeyW1WEfGFvIBFhOqB5w" name="to()" content="return reclamoVar.correoCliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_TOmeym1WEfGFvIBFhOqB5w" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmey21WEfGFvIBFhOqB5w" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_TOmezG1WEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmezW1WEfGFvIBFhOqB5w" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_TOmezm1WEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOmez21WEfGFvIBFhOqB5w" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_TOme0G1WEfGFvIBFhOqB5w" name="subject()" content="'Resolución de Reclamo - Olva Courier (Rechazado)'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOme0W1WEfGFvIBFhOqB5w" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_TOme0m1WEfGFvIBFhOqB5w" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOme021WEfGFvIBFhOqB5w" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_TOme1G1WEfGFvIBFhOqB5w" name="newScript()" content="return &quot;Estimado cliente,\n\n&quot; +&#xD;&#xA;&quot;Tras revisar su reclamo asociado al tracking &quot; + reclamoVar.numeroTracking + &quot;, le informamos que ha sido RECHAZADO.\n\n&quot; +&#xD;&#xA;&quot;Motivo: El paquete contenía artículos prohibidos o no cumplía con los lineamientos de embalaje, lo cual exime de responsabilidad a la empresa según nuestros Términos y Condiciones.\n\n&quot; +&#xD;&#xA;&quot;Atentamente,\nAtención al Cliente - Olva Courier.&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_TOme1W1WEfGFvIBFhOqB5w" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOme1m1WEfGFvIBFhOqB5w" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_TOme121WEfGFvIBFhOqB5w"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOme2G1WEfGFvIBFhOqB5w" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_TOme2W1WEfGFvIBFhOqB5w" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOme2m1WEfGFvIBFhOqB5w" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_TOme221WEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_TOme3G1WEfGFvIBFhOqB5w" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_TOme3W1WEfGFvIBFhOqB5w"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_6wnYw21IEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_6wnYxG1IEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_6wnYxW1IEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_6wnYx21IEfGFvIBFhOqB5w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_6wnYxm1IEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_56DFQHUsEfGKnvRhvJRGAg" name="Redactar carta de rechazo" outgoing="_i3fLBG1JEfGFvIBFhOqB5w" incoming="_cQQ_YG1JEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_cQQYUW1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_cQQYUG1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_cQQYUm1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_bCfFwHUtEfGKnvRhvJRGAg" name="correoCartaRechazo" definitionId="email" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_bCfFwXUtEfGKnvRhvJRGAg" definitionId="email" version="1.3.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfFwnUtEfGKnvRhvJRGAg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_bCfFw3UtEfGKnvRhvJRGAg" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfFxHUtEfGKnvRhvJRGAg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_bCfFxXUtEfGKnvRhvJRGAg" name="1025" content="1025" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfFxnUtEfGKnvRhvJRGAg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_bCfFx3UtEfGKnvRhvJRGAg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfFyHUtEfGKnvRhvJRGAg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_bCfFyXUtEfGKnvRhvJRGAg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfFynUtEfGKnvRhvJRGAg" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_bCfFy3UtEfGKnvRhvJRGAg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfFzHUtEfGKnvRhvJRGAg" key="authType">
                <expression xmi:type="expression:Expression" xmi:id="_bCfFzXUtEfGKnvRhvJRGAg" name="Basic authentication" content="Basic authentication" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfFznUtEfGKnvRhvJRGAg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_bCfFz3UtEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF0HUtEfGKnvRhvJRGAg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF0XUtEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF0nUtEfGKnvRhvJRGAg" key="oauth2AccessToken">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF03UtEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF1HUtEfGKnvRhvJRGAg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF1XUtEfGKnvRhvJRGAg" name="notificaciones@olvacourier.com" content="notificaciones@olvacourier.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF1nUtEfGKnvRhvJRGAg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF13UtEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF2HUtEfGKnvRhvJRGAg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF2XUtEfGKnvRhvJRGAg" name="to()" content="return reclamoVar.correoCliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_nVd6UHUtEfGKnvRhvJRGAg" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF2nUtEfGKnvRhvJRGAg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF23UtEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF3HUtEfGKnvRhvJRGAg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF3XUtEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF3nUtEfGKnvRhvJRGAg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF33UtEfGKnvRhvJRGAg" name="subject()" content="return 'Actualización de su Reclamo - Infundado'" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF4HUtEfGKnvRhvJRGAg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF4XUtEfGKnvRhvJRGAg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF4nUtEfGKnvRhvJRGAg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF43UtEfGKnvRhvJRGAg" name="newScript()" content="return &quot;Estimado cliente,\n\n&quot; +&#xD;&#xA;&quot;Tras revisar su reclamo asociado al tracking &quot; + reclamoVar.numeroTracking + &quot;, le informamos que ha sido determinado como INFUNDADO por nuestra área de operaciones.\n\n&quot; +&#xD;&#xA;&quot;Motivo de la resolución:\n&quot; + reclamoVar.dictamenOperaciones + &quot;\n\n&quot; +&#xD;&#xA;&quot;Atentamente,\nAtención al Cliente - Olva Courier.&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_9MqQEHUtEfGKnvRhvJRGAg" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF5XUtEfGKnvRhvJRGAg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_bCfF5nUtEfGKnvRhvJRGAg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF53UtEfGKnvRhvJRGAg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF6HUtEfGKnvRhvJRGAg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF6XUtEfGKnvRhvJRGAg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_bCfF6nUtEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_bCfF63UtEfGKnvRhvJRGAg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_bCfF7HUtEfGKnvRhvJRGAg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_cQQYU21JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_cQQYVG1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_cQQYVW1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_cQQYV21JEfGFvIBFhOqB5w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_cQQYVm1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_1EvQgG1HEfGFvIBFhOqB5w" name="Operaciones" actor="_Obs68G1XEfGFvIBFhOqB5w">
        <elements xmi:type="process:Task" xmi:id="_Iu5RgG1JEfGFvIBFhOqB5w" documentation="Acción: Revisa manifiestos o si hubo 2 intentos fallidos de entrega&#xD;&#xA;Output: Actualiza la variable dictamenOperaciones a &quot;Fundado&quot; o &quot;Infundado&quot;" name="Investigar Trazabilidad del Envío" outgoing="_XZh58G1JEfGFvIBFhOqB5w" incoming="_BwQEYG1JEfGFvIBFhOqB5w" actor="_Obs68G1XEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_BwPdUW1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_BwPdUG1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_BwPdUm1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_L087IG1XEfGFvIBFhOqB5w">
            <leftOperand xmi:type="expression:Expression" xmi:id="_L087IW1XEfGFvIBFhOqB5w" name="reclamoVar" content="reclamoVar" type="TYPE_VARIABLE" returnType="com.company.model.Reclamo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_L087Im1XEfGFvIBFhOqB5w" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_L087I21XEfGFvIBFhOqB5w" name="reclamoVarInput.dictamenOperaciones" content="reclamoVarInput?.dictamenOperaciones" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_L087JG1XEfGFvIBFhOqB5w" name="reclamoVarInput" type="COMPLEX" createMode="false"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_L087JW1XEfGFvIBFhOqB5w" type="JAVA_METHOD" expression="setDictamenOperaciones">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_BwPdU21JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_BwPdVG1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_BwPdVW1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_BwPdV21JEfGFvIBFhOqB5w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_BwPdVm1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_Iu5Rim1JEfGFvIBFhOqB5w">
            <targetForm xmi:type="expression:Expression" xmi:id="_T_8moG1XEfGFvIBFhOqB5w" name="investigarTrazabilidad" content="6e47e56a-a773-446d-aba3-d0844d79236c" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_Iu5RiW1JEfGFvIBFhOqB5w">
            <inputs xmi:type="process:ContractInput" xmi:id="_L08UEG1XEfGFvIBFhOqB5w" name="reclamoVarInput" type="COMPLEX" dataReference="reclamoVar" createMode="false">
              <inputs xmi:type="process:ContractInput" xmi:id="_L08UEW1XEfGFvIBFhOqB5w" name="dictamenOperaciones" createMode="false"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="___cPAHVUEfGkzq9efzNXtg" expression="return reclamoVarInput.dictamenOperaciones != null &amp;&amp; !reclamoVarInput.dictamenOperaciones.trim().isEmpty()" errorMessage="Debe ingresar el detalle del dictamen de operaciones." name="validarDictamen">
              <inputNames>reclamoVarInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_Iu5RjG1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_YAo9QG1JEfGFvIBFhOqB5w" name="¿Reclamo Fundado?" outgoing="_cQQ_YG1JEfGFvIBFhOqB5w _15OWl21JEfGFvIBFhOqB5w" incoming="_XZh58G1JEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_XZgr0m1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_XZgr0W1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_XZgr021JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_2OHBcG1JEfGFvIBFhOqB5w" name="¿Envío Asegurado y > S/ 100?" outgoing="_8Ydq4G1JEfGFvIBFhOqB5w _CvsSsG1KEfGFvIBFhOqB5w" incoming="_15OWl21JEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_15OWkW1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_15OWkG1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_15OWkm1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_F6TNgG1KEfGFvIBFhOqB5w" name="Asignar solo devolución de flete" outgoing="_SdpHYG1MEfGFvIBFhOqB5w" incoming="_FYFRQ21KEfGFvIBFhOqB5w" actor="_Obs68G1XEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_FYEqMm1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_FYEqMW1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_FYEqM21KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_FYEqNG1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_FYEqNW1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_FYEqNm1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_FYEqOG1KEfGFvIBFhOqB5w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_FYEqN21KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_F6T0mW1KEfGFvIBFhOqB5w">
            <targetForm xmi:type="expression:Expression" xmi:id="_VHHGMG1bEfGFvIBFhOqB5w" name="devolucionFleteSinBoleta" content="1ce3701e-f694-49f8-ad89-b411c00117cf" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_F6T0mG1KEfGFvIBFhOqB5w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_F6T0m21KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_G7VzwG1KEfGFvIBFhOqB5w" name="Asignar Devolución de Flete o Nota de Crédito" outgoing="_RtSogG1MEfGFvIBFhOqB5w" incoming="_8Ydq4G1JEfGFvIBFhOqB5w" actor="_Obs68G1XEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_8Yccwm1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_8YccwW1JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_8Yccw21JEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_Il2K0G8YEfGgjsG-ztl8Nw">
            <leftOperand xmi:type="expression:Expression" xmi:id="_Il2K0W8YEfGgjsG-ztl8Nw" name="reclamoVar" content="reclamoVar" type="TYPE_VARIABLE" returnType="com.company.model.Reclamo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Kh0IQG8YEfGgjsG-ztl8Nw" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_Il2K0m8YEfGgjsG-ztl8Nw" name="newScript()" content="reclamoVar.setTipoDevolucion(tipoDevolucionInput)&#xD;&#xA;return reclamoVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Reclamo">
              <referencedElements xmi:type="process:ContractInput" xmi:id="_QZd4IG8YEfGgjsG-ztl8Nw" name="tipoDevolucionInput">
                <mapping xmi:type="process:ContractInputMapping" xmi:id="_QZd4IW8YEfGgjsG-ztl8Nw"/>
              </referencedElements>
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QZd4Im8YEfGgjsG-ztl8Nw" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
            </rightOperand>
            <operator xmi:type="expression:Operator" xmi:id="_Il2K028YEfGgjsG-ztl8Nw" type="ASSIGNMENT"/>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_8YdD0G1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_8YdD0W1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_8YdD0m1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_8YdD1G1JEfGFvIBFhOqB5w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_8YdD021JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_G7Wa2W1KEfGFvIBFhOqB5w">
            <targetForm xmi:type="expression:Expression" xmi:id="_beN8wG1cEfGFvIBFhOqB5w" name="devolucionFleteNotaCredito" content="7ca4a155-e5a2-4f4d-8821-cfc24c8085b5" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_G7Wa2G1KEfGFvIBFhOqB5w">
            <inputs xmi:type="process:ContractInput" xmi:id="_-XW9kG8XEfGgjsG-ztl8Nw" name="tipoDevolucionInput">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_-XW9kW8XEfGgjsG-ztl8Nw"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_x2JOgHVTEfGkzq9efzNXtg" expression="return tipoDevolucionInput == &quot;Flete&quot; || tipoDevolucionInput == &quot;Nota de Crédito&quot;" errorMessage="Debe seleccionar Flete o Nota de Crédito." name="validarOpcionDevolucion">
              <inputNames>tipoDevolucionInput</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_G7Wa221KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:XORGateway" xmi:id="_dpjREG1KEfGFvIBFhOqB5w" name="¿Presenta Boleta de Compra?" outgoing="_FYFRQ21KEfGFvIBFhOqB5w _Jrsbg21KEfGFvIBFhOqB5w" incoming="_CvsSsG1KEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Cvrrom1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_CvrroW1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Cvrro21KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <elements xmi:type="process:Lane" xmi:id="_14H1QG1HEfGFvIBFhOqB5w" name="Finanzas" actor="_6ANU4G1bEfGFvIBFhOqB5w">
        <elements xmi:type="process:Task" xmi:id="_PjIwAG1KEfGFvIBFhOqB5w" name="Liquidar 80 porciento del valor + Flete" outgoing="_To-kC21KEfGFvIBFhOqB5w" incoming="_Jrsbg21KEfGFvIBFhOqB5w" actor="_6ANU4G1bEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Jrr0cW1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Jrr0cG1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Jrr0cm1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Jrr0c21KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Jrr0dG1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Jrr0dW1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Jrr0d21KEfGFvIBFhOqB5w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Jrr0dm1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_PjIwCm1KEfGFvIBFhOqB5w">
            <targetForm xmi:type="expression:Expression" xmi:id="_6_x7gG1bEfGFvIBFhOqB5w" name="liquidacionOchentaPorciento" content="46a7db4b-b545-416f-acfa-4dead741067a" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_PjIwCW1KEfGFvIBFhOqB5w"/>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_PjIwDG1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:Task" xmi:id="_UqqqgG1KEfGFvIBFhOqB5w" name="Ejecutar Compensación en Sistema" outgoing="_Vp8WPG1KEfGFvIBFhOqB5w" incoming="_To-kC21KEfGFvIBFhOqB5w _RtSogG1MEfGFvIBFhOqB5w _SdpHYG1MEfGFvIBFhOqB5w" actor="_6ANU4G1bEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_To-kAW1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_To-kAG1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_To-kAm1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <operations xmi:type="expression:Operation" xmi:id="_QNsCQHU0EfGKnvRhvJRGAg">
            <leftOperand xmi:type="expression:Expression" xmi:id="_QNsCQXU0EfGKnvRhvJRGAg" name="reclamoVar" content="reclamoVar" type="TYPE_VARIABLE" returnType="com.company.model.Reclamo">
              <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_QNsCQnU0EfGKnvRhvJRGAg" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
            </leftOperand>
            <rightOperand xmi:type="expression:Expression" xmi:id="_QNsCQ3U0EfGKnvRhvJRGAg" name="codigoOperacion" content="codigoOperacion"/>
            <operator xmi:type="expression:Operator" xmi:id="_QNsCRXU0EfGKnvRhvJRGAg" type="JAVA_METHOD" expression="setCodigoOperacion">
              <inputTypes>java.lang.String</inputTypes>
            </operator>
          </operations>
          <loopCondition xmi:type="expression:Expression" xmi:id="_To-kA21KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_To-kBG1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_To-kBW1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_To-kB21KEfGFvIBFhOqB5w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_To-kBm1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <formMapping xmi:type="process:FormMapping" xmi:id="_UqrRmW1KEfGFvIBFhOqB5w">
            <targetForm xmi:type="expression:Expression" xmi:id="_UQILMG8ZEfGgjsG-ztl8Nw" name="ejecutarCompensacion" content="cd0b513f-97f4-4aab-a96d-91a0e8a1d3d7" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
          </formMapping>
          <contract xmi:type="process:Contract" xmi:id="_UqrRmG1KEfGFvIBFhOqB5w">
            <inputs xmi:type="process:ContractInput" xmi:id="_Th8BQHU0EfGKnvRhvJRGAg" name="codigoOperacion">
              <mapping xmi:type="process:ContractInputMapping" xmi:id="_Th8BQXU0EfGKnvRhvJRGAg"/>
            </inputs>
            <constraints xmi:type="process:ContractConstraint" xmi:id="_cNTBUHVUEfGkzq9efzNXtg" expression="return codigoOperacion != null &amp;&amp; !codigoOperacion.trim().isEmpty()" errorMessage="El código de operación contable es obligatorio." name="validarCodigoObligatorio">
              <inputNames>codigoOperacion</inputNames>
            </constraints>
          </contract>
          <expectedDuration xmi:type="expression:Expression" xmi:id="_UqrRm21KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Long" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:ServiceTask" xmi:id="_Vp8WMG1KEfGFvIBFhOqB5w" name="Notificar Resolución al Cliente" outgoing="_YCtkZ21KEfGFvIBFhOqB5w" incoming="_Vp8WPG1KEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_Vp8WMm1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_Vp8WMW1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_Vp8WM21KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <connectors xmi:type="process:Connector" xmi:id="_Xu4NsHUyEfGKnvRhvJRGAg" name="correoResolucionCliente" definitionId="email" event="ON_ENTER" definitionVersion="1.3.0">
            <configuration xmi:type="connectorconfiguration:ConnectorConfiguration" xmi:id="_Xu4NsXUyEfGKnvRhvJRGAg" definitionId="email" version="1.3.0" modelVersion="9">
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NsnUyEfGKnvRhvJRGAg" key="smtpHost">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4Ns3UyEfGKnvRhvJRGAg" name="localhost" content="localhost" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NtHUyEfGKnvRhvJRGAg" key="smtpPort">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4NtXUyEfGKnvRhvJRGAg" name="1025" content="1025" returnType="java.lang.Integer" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NtnUyEfGKnvRhvJRGAg" key="sslSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4Nt3UyEfGKnvRhvJRGAg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NuHUyEfGKnvRhvJRGAg" key="starttlsSupport">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4NuXUyEfGKnvRhvJRGAg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NunUyEfGKnvRhvJRGAg" key="trustCertificate">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4Nu3UyEfGKnvRhvJRGAg" name="false" content="false" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NvHUyEfGKnvRhvJRGAg" key="authType">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4NvXUyEfGKnvRhvJRGAg" name="Basic authentication" content="Basic authentication" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NvnUyEfGKnvRhvJRGAg" key="userName">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4Nv3UyEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NwHUyEfGKnvRhvJRGAg" key="password">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4NwXUyEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NwnUyEfGKnvRhvJRGAg" key="oauth2AccessToken">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4Nw3UyEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NxHUyEfGKnvRhvJRGAg" key="from">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4NxXUyEfGKnvRhvJRGAg" name="notificaciones@olvacourier.com" content="notificaciones@olvacourier.com" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NxnUyEfGKnvRhvJRGAg" key="returnPath">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4Nx3UyEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NyHUyEfGKnvRhvJRGAg" key="to">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4NyXUyEfGKnvRhvJRGAg" name="to()" content="return reclamoVar.correoCliente" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Xu4NynUyEfGKnvRhvJRGAg" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4Ny3UyEfGKnvRhvJRGAg" key="bcc">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4NzHUyEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4NzXUyEfGKnvRhvJRGAg" key="cc">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4NznUyEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4Nz3UyEfGKnvRhvJRGAg" key="subject">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4N0HUyEfGKnvRhvJRGAg" name="subject()" content="return &quot;Resolución de Reclamo Aprobada - Tracking &quot; + reclamoVar.numeroTracking" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_Xu4N0XUyEfGKnvRhvJRGAg" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4N0nUyEfGKnvRhvJRGAg" key="html">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4N03UyEfGKnvRhvJRGAg" name="true" content="true" returnType="java.lang.Boolean" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4N1HUyEfGKnvRhvJRGAg" key="message">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4N1XUyEfGKnvRhvJRGAg" name="newScript()" content="return &quot;Estimado cliente,\n\n&quot; +&#xD;&#xA;&quot;Nos complace informarle que su reclamo asociado al tracking &quot; + reclamoVar.numeroTracking + &quot; ha sido resuelto a su favor.\n\n&quot; +&#xD;&#xA;&quot;Detalles de la transacción:\n&quot; +&#xD;&#xA;&quot;- Tipo de Devolución: &quot; + reclamoVar.tipoDevolucion + &quot;\n&quot; +&#xD;&#xA;&quot;- Código de Operación Contable: &quot; + reclamoVar.codigoOperacion + &quot;\n\n&quot; +&#xD;&#xA;&quot;El abono/nota de crédito correspondiente ha sido procesado exitosamente en nuestro sistema.\n\n&quot; +&#xD;&#xA;&quot;Atentamente,\nÁrea de Finanzas - Olva Courier.&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnTypeFixed="true">
                  <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_neC_0HUzEfGKnvRhvJRGAg" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
                </expression>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4N13UyEfGKnvRhvJRGAg" key="headers">
                <expression xmi:type="expression:TableExpression" xmi:id="_Xu4N2HUyEfGKnvRhvJRGAg"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4N2XUyEfGKnvRhvJRGAg" key="charset">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4N2nUyEfGKnvRhvJRGAg" name="UTF-8" content="UTF-8" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4N23UyEfGKnvRhvJRGAg" key="replyTo">
                <expression xmi:type="expression:Expression" xmi:id="_Xu4N3HUyEfGKnvRhvJRGAg" content="" returnTypeFixed="true"/>
              </parameters>
              <parameters xmi:type="connectorconfiguration:ConnectorParameter" xmi:id="_Xu4N3XUyEfGKnvRhvJRGAg" key="attachments">
                <expression xmi:type="expression:ListExpression" xmi:id="_Xu4N3nUyEfGKnvRhvJRGAg"/>
              </parameters>
            </configuration>
          </connectors>
          <loopCondition xmi:type="expression:Expression" xmi:id="_Vp8WNG1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
          <loopMaximum xmi:type="expression:Expression" xmi:id="_Vp8WNW1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <cardinalityExpression xmi:type="expression:Expression" xmi:id="_Vp8WNm1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Integer" returnTypeFixed="true"/>
          <iteratorExpression xmi:type="expression:Expression" xmi:id="_Vp8WOG1KEfGFvIBFhOqB5w" name="multiInstanceIterator" content="multiInstanceIterator" type="MULTIINSTANCE_ITERATOR_TYPE" returnType="java.lang.Object" returnTypeFixed="true"/>
          <completionCondition xmi:type="expression:Expression" xmi:id="_Vp8WN21KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
        </elements>
        <elements xmi:type="process:EndEvent" xmi:id="_YCs9UG1KEfGFvIBFhOqB5w" name="Reclamo Cerrado" incoming="_YCtkZ21KEfGFvIBFhOqB5w">
          <dynamicLabel xmi:type="expression:Expression" xmi:id="_YCtkYW1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <dynamicDescription xmi:type="expression:Expression" xmi:id="_YCtkYG1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
          <stepSummary xmi:type="expression:Expression" xmi:id="_YCtkYm1KEfGFvIBFhOqB5w" name="" content="" returnTypeFixed="true"/>
        </elements>
      </elements>
      <data xmi:type="process:BusinessObjectData" xmi:id="_MKstMG1NEfGFvIBFhOqB5w" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo">
        <defaultValue xmi:type="expression:Expression" xmi:id="_v-mgkG8dEfGgjsG-ztl8Nw" name="initReclamoVar()" content="def reclamoVar = new com.company.model.Reclamo()&#xD;&#xA;reclamoVar.numeroTracking = reclamoVarInput?.numeroTracking&#xD;&#xA;reclamoVar.motivoReclamo = reclamoVarInput?.motivoReclamo&#xD;&#xA;reclamoVar.valorDeclarado = reclamoVarInput?.valorDeclarado?.toFloat()&#xD;&#xA;reclamoVar.correoCliente = reclamoVarInput?.correoCliente&#xD;&#xA;return reclamoVar" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="com.company.model.Reclamo">
          <referencedElements xmi:type="process:ContractInput" xmi:id="_v-mgkW8dEfGgjsG-ztl8Nw" name="reclamoVarInput" type="COMPLEX"/>
        </defaultValue>
      </data>
      <formMapping xmi:type="process:FormMapping" xmi:id="_nKx3JG1HEfGFvIBFhOqB5w">
        <targetForm xmi:type="expression:Expression" xmi:id="_XpKlhm1WEfGFvIBFhOqB5w" name="portalReclamos" content="648f5088-29e1-40ee-abf7-6b420de32af8" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </formMapping>
      <overviewFormMapping xmi:type="process:FormMapping" xmi:id="_nKx3Jm1HEfGFvIBFhOqB5w">
        <targetForm xmi:type="expression:Expression" xmi:id="_2l1vwG8cEfGgjsG-ztl8Nw" name="portalReclamos" content="648f5088-29e1-40ee-abf7-6b420de32af8" type="FORM_REFERENCE_TYPE" returnTypeFixed="true"/>
      </overviewFormMapping>
      <connections xmi:type="process:SequenceFlow" xmi:id="_1CR89G1IEfGFvIBFhOqB5w" target="_1nkbUG1IEfGFvIBFhOqB5w" source="_zLk6AG1IEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_1CR89W1IEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_1CR89m1IEfGFvIBFhOqB5w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_6wn_0G1IEfGFvIBFhOqB5w" name="No" target="_1zH1YG9IEfGjyPnck1rwvA" source="_1nkbUG1IEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_6wn_0W1IEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_6wn_0m1IEfGFvIBFhOqB5w" name="newScript()" content="return reclamoVar.articuloProhibido == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_1itk8G1SEfGFvIBFhOqB5w" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_BwQEYG1JEfGFvIBFhOqB5w" name="Sí" target="_Iu5RgG1JEfGFvIBFhOqB5w" source="_1nkbUG1IEfGFvIBFhOqB5w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_BwQEYW1JEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_BwQEYm1JEfGFvIBFhOqB5w" name="newScript()" content="return true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FJ3rkG1JEfGFvIBFhOqB5w" target="_FJ2dcG1JEfGFvIBFhOqB5w" source="_1zH1YG9IEfGjyPnck1rwvA">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FJ3rkW1JEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_FJ3rkm1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_XZh58G1JEfGFvIBFhOqB5w" target="_YAo9QG1JEfGFvIBFhOqB5w" source="_Iu5RgG1JEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_XZh58W1JEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_XZh58m1JEfGFvIBFhOqB5w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_cQQ_YG1JEfGFvIBFhOqB5w" name="No" target="_56DFQHUsEfGKnvRhvJRGAg" source="_YAo9QG1JEfGFvIBFhOqB5w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_cQQ_YW1JEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_cQQ_Ym1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_i3fLBG1JEfGFvIBFhOqB5w" target="_i3ej8G1JEfGFvIBFhOqB5w" source="_56DFQHUsEfGKnvRhvJRGAg">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_i3fLBW1JEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_i3fLBm1JEfGFvIBFhOqB5w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_15OWl21JEfGFvIBFhOqB5w" name="Sí" target="_2OHBcG1JEfGFvIBFhOqB5w" source="_YAo9QG1JEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_15OWmG1JEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_15OWmW1JEfGFvIBFhOqB5w" name="newScript()" content="return reclamoVar.dictamenOperaciones == &quot;Fundado&quot;" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_RcVIcG1ZEfGFvIBFhOqB5w" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_8Ydq4G1JEfGFvIBFhOqB5w" name="No" target="_G7VzwG1KEfGFvIBFhOqB5w" source="_2OHBcG1JEfGFvIBFhOqB5w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_8Ydq4W1JEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_8Ydq4m1JEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_CvsSsG1KEfGFvIBFhOqB5w" name="Sí" target="_dpjREG1KEfGFvIBFhOqB5w" source="_2OHBcG1JEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_CvsSsW1KEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_CvsSsm1KEfGFvIBFhOqB5w" name="newScript()" content="return reclamoVar.valorDeclarado > 100.0f &amp;&amp; reclamoVar.tieneSeguro == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_bW0boG1ZEfGFvIBFhOqB5w" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_FYFRQ21KEfGFvIBFhOqB5w" name="No" target="_F6TNgG1KEfGFvIBFhOqB5w" source="_dpjREG1KEfGFvIBFhOqB5w" isDefault="true">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_FYFRRG1KEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_FYFRRW1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Jrsbg21KEfGFvIBFhOqB5w" name="Sí" target="_PjIwAG1KEfGFvIBFhOqB5w" source="_dpjREG1KEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_JrsbhG1KEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_JrsbhW1KEfGFvIBFhOqB5w" name="newScript()" content="return reclamoVar.tieneBoleta == true" interpreter="GROOVY" type="TYPE_READ_ONLY_SCRIPT" returnType="java.lang.Boolean" returnTypeFixed="true">
          <referencedElements xmi:type="process:BusinessObjectData" xmi:id="_EnVhEG1bEfGFvIBFhOqB5w" name="reclamoVar" dataType="_nKx3RG1HEfGFvIBFhOqB5w" className="com.company.model.Reclamo"/>
        </condition>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_To-kC21KEfGFvIBFhOqB5w" target="_UqqqgG1KEfGFvIBFhOqB5w" source="_PjIwAG1KEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_To-kDG1KEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_To-kDW1KEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_Vp8WPG1KEfGFvIBFhOqB5w" target="_Vp8WMG1KEfGFvIBFhOqB5w" source="_UqqqgG1KEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_Vp89QG1KEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_Vp89QW1KEfGFvIBFhOqB5w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_YCtkZ21KEfGFvIBFhOqB5w" target="_YCs9UG1KEfGFvIBFhOqB5w" source="_Vp8WMG1KEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_YCtkaG1KEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_YCtkaW1KEfGFvIBFhOqB5w" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_RtSogG1MEfGFvIBFhOqB5w" target="_UqqqgG1KEfGFvIBFhOqB5w" source="_G7VzwG1KEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_RtSogW1MEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_RtSogm1MEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_SdpHYG1MEfGFvIBFhOqB5w" target="_UqqqgG1KEfGFvIBFhOqB5w" source="_F6TNgG1KEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_SdpucG1MEfGFvIBFhOqB5w"/>
        <condition xmi:type="expression:Expression" xmi:id="_SdpucW1MEfGFvIBFhOqB5w" name="" content="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <connections xmi:type="process:SequenceFlow" xmi:id="_2zc4gG8dEfGgjsG-ztl8Nw" target="_zLk6AG1IEfGFvIBFhOqB5w" source="_nKx3E21HEfGFvIBFhOqB5w">
        <decisionTable xmi:type="decision:DecisionTable" xmi:id="_2zf70G8dEfGgjsG-ztl8Nw"/>
        <condition xmi:type="expression:Expression" xmi:id="_2zf70W8dEfGgjsG-ztl8Nw" name="" returnType="java.lang.Boolean" returnTypeFixed="true"/>
      </connections>
      <actors xmi:type="process:Actor" xmi:id="_P_qhsG1PEfGFvIBFhOqB5w" name="cliente" initiator="true"/>
      <actors xmi:type="process:Actor" xmi:id="_DM1BAG1SEfGFvIBFhOqB5w" name="atc"/>
      <actors xmi:type="process:Actor" xmi:id="_Obs68G1XEfGFvIBFhOqB5w" name="operador"/>
      <actors xmi:type="process:Actor" xmi:id="_6ANU4G1bEfGFvIBFhOqB5w" name="finanzas"/>
      <contract xmi:type="process:Contract" xmi:id="_nKx3LG1HEfGFvIBFhOqB5w">
        <inputs xmi:type="process:ContractInput" xmi:id="_v-l5gG8dEfGgjsG-ztl8Nw" name="reclamoVarInput" type="COMPLEX" dataReference="reclamoVar">
          <inputs xmi:type="process:ContractInput" xmi:id="_v-l5gW8dEfGgjsG-ztl8Nw" name="numeroTracking"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_v-l5gm8dEfGgjsG-ztl8Nw" name="motivoReclamo"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_v-l5g28dEfGgjsG-ztl8Nw" name="valorDeclarado" type="DECIMAL"/>
          <inputs xmi:type="process:ContractInput" xmi:id="_v-l5hG8dEfGgjsG-ztl8Nw" name="correoCliente"/>
        </inputs>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_v-l5hW8dEfGgjsG-ztl8Nw" expression="reclamoVarInput?.numeroTracking != null" errorMessage="numeroTracking is mandatory for Reclamo" name="mandatory_reclamoVarInput_numeroTracking">
          <inputNames>reclamoVarInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_v-l5hm8dEfGgjsG-ztl8Nw" expression="reclamoVarInput?.motivoReclamo != null" errorMessage="motivoReclamo is mandatory for Reclamo" name="mandatory_reclamoVarInput_motivoReclamo">
          <inputNames>reclamoVarInput</inputNames>
        </constraints>
        <constraints xmi:type="process:ContractConstraint" xmi:id="_v-l5h28dEfGgjsG-ztl8Nw" expression="reclamoVarInput?.correoCliente != null" errorMessage="correoCliente is mandatory for Reclamo" name="mandatory_reclamoVarInput_correoCliente">
          <inputNames>reclamoVarInput</inputNames>
        </constraints>
      </contract>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_nKx3LW1HEfGFvIBFhOqB5w">
        <name xmi:type="expression:Expression" xmi:id="_nKx3Lm1HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_nKx3L21HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_nKx3MG1HEfGFvIBFhOqB5w">
        <name xmi:type="expression:Expression" xmi:id="_nKx3MW1HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_nKx3Mm1HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_nKx3M21HEfGFvIBFhOqB5w">
        <name xmi:type="expression:Expression" xmi:id="_nKx3NG1HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_nKx3NW1HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_nKx3Nm1HEfGFvIBFhOqB5w">
        <name xmi:type="expression:Expression" xmi:id="_nKx3N21HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_nKx3OG1HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
      <searchIndexes xmi:type="process:SearchIndex" xmi:id="_nKx3OW1HEfGFvIBFhOqB5w">
        <name xmi:type="expression:Expression" xmi:id="_nKx3Om1HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
        <value xmi:type="expression:Expression" xmi:id="_nKx3O21HEfGFvIBFhOqB5w" content="" returnTypeFixed="true"/>
      </searchIndexes>
    </elements>
    <datatypes xmi:type="process:BooleanType" xmi:id="_nKx3PG1HEfGFvIBFhOqB5w" name="Boolean"/>
    <datatypes xmi:type="process:DateType" xmi:id="_nKx3PW1HEfGFvIBFhOqB5w" name="Date"/>
    <datatypes xmi:type="process:IntegerType" xmi:id="_nKx3Pm1HEfGFvIBFhOqB5w" name="Integer"/>
    <datatypes xmi:type="process:LongType" xmi:id="_nKx3P21HEfGFvIBFhOqB5w" name="Long"/>
    <datatypes xmi:type="process:DoubleType" xmi:id="_nKx3QG1HEfGFvIBFhOqB5w" name="Double"/>
    <datatypes xmi:type="process:StringType" xmi:id="_nKx3QW1HEfGFvIBFhOqB5w" name="Text"/>
    <datatypes xmi:type="process:JavaType" xmi:id="_nKx3Qm1HEfGFvIBFhOqB5w" name="Java_object"/>
    <datatypes xmi:type="process:XMLType" xmi:id="_nKx3Q21HEfGFvIBFhOqB5w" name="XML"/>
    <datatypes xmi:type="process:BusinessObjectType" xmi:id="_nKx3RG1HEfGFvIBFhOqB5w" name="Business_Object"/>
  </process:MainProcess>
  <notation:Diagram xmi:id="_nKx3RW1HEfGFvIBFhOqB5w" type="Process" element="_nKx3EG1HEfGFvIBFhOqB5w" name="MiDiagrama" measurementUnit="Pixel">
    <children xmi:type="notation:Node" xmi:id="_nKx3Rm1HEfGFvIBFhOqB5w" type="2007" element="_nKx3EW1HEfGFvIBFhOqB5w">
      <children xmi:type="notation:DecorationNode" xmi:id="_nKx3R21HEfGFvIBFhOqB5w" type="5008"/>
      <children xmi:type="notation:DecorationNode" xmi:id="_nKx3SG1HEfGFvIBFhOqB5w" type="7001">
        <children xmi:type="notation:Node" xmi:id="_nKx3SW1HEfGFvIBFhOqB5w" type="3007" element="_nKx3Em1HEfGFvIBFhOqB5w">
          <children xmi:type="notation:DecorationNode" xmi:id="_nKx3Sm1HEfGFvIBFhOqB5w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_nKx3S21HEfGFvIBFhOqB5w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_nKx3T21HEfGFvIBFhOqB5w" type="3002" element="_nKx3E21HEfGFvIBFhOqB5w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_nKx3UG1HEfGFvIBFhOqB5w" type="5024">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_nKx3UW1HEfGFvIBFhOqB5w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nKx3Um1HEfGFvIBFhOqB5w" x="60" y="68"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_nKx3U21HEfGFvIBFhOqB5w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_nKx3VG1HEfGFvIBFhOqB5w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_nKx3VW1HEfGFvIBFhOqB5w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_nKx3Vm1HEfGFvIBFhOqB5w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nKx3V21HEfGFvIBFhOqB5w"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_uZrtwG1HEfGFvIBFhOqB5w" type="3007" element="_uZpRgG1HEfGFvIBFhOqB5w">
          <children xmi:type="notation:DecorationNode" xmi:id="_uZrtxW1HEfGFvIBFhOqB5w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_uZsU0G1HEfGFvIBFhOqB5w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_zLlhEG1IEfGFvIBFhOqB5w" type="3005" element="_zLk6AG1IEfGFvIBFhOqB5w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_zLlhEm1IEfGFvIBFhOqB5w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_zLlhEW1IEfGFvIBFhOqB5w" x="165" y="97" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1nlpc21IEfGFvIBFhOqB5w" type="3008" element="_1nkbUG1IEfGFvIBFhOqB5w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_1nlpdW1IEfGFvIBFhOqB5w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_1nlpdm1IEfGFvIBFhOqB5w" y="-58"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1nlpdG1IEfGFvIBFhOqB5w" x="384" y="105" width="43" height="43"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_FJ3Eg21JEfGFvIBFhOqB5w" type="3003" element="_FJ2dcG1JEfGFvIBFhOqB5w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_FJ3EhW1JEfGFvIBFhOqB5w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_FJ3Ehm1JEfGFvIBFhOqB5w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_FJ3EhG1JEfGFvIBFhOqB5w" x="784" y="109"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_i3fLAG1JEfGFvIBFhOqB5w" type="3003" element="_i3ej8G1JEfGFvIBFhOqB5w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_i3fLAm1JEfGFvIBFhOqB5w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_i3fLA21JEfGFvIBFhOqB5w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_i3fLAW1JEfGFvIBFhOqB5w" x="1073" y="107"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_1zJDh29IEfGjyPnck1rwvA" type="3027" element="_1zH1YG9IEfGjyPnck1rwvA" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_1zJqkG9IEfGjyPnck1rwvA" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1zJDiG9IEfGjyPnck1rwvA" x="535" y="92" width="157" height="76"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_56M2QHUsEfGKnvRhvJRGAg" type="3027" element="_56DFQHUsEfGKnvRhvJRGAg" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_56M2QnUsEfGKnvRhvJRGAg" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_56M2QXUsEfGKnvRhvJRGAg" x="870" y="99" width="120" height="60"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_uZrtwW1HEfGFvIBFhOqB5w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_uZrtwm1HEfGFvIBFhOqB5w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_uZrtw21HEfGFvIBFhOqB5w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_uZsU0W1HEfGFvIBFhOqB5w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_uZrtxG1HEfGFvIBFhOqB5w" x="369" y="180"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_1EvQgW1HEfGFvIBFhOqB5w" type="3007" element="_1EvQgG1HEfGFvIBFhOqB5w">
          <children xmi:type="notation:DecorationNode" xmi:id="_1Ev3kG1HEfGFvIBFhOqB5w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_1Ev3kW1HEfGFvIBFhOqB5w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_Iu5RjW1JEfGFvIBFhOqB5w" type="3005" element="_Iu5RgG1JEfGFvIBFhOqB5w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Iu5Rj21JEfGFvIBFhOqB5w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Iu5Rjm1JEfGFvIBFhOqB5w" x="346" y="99" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YApkU21JEfGFvIBFhOqB5w" type="3008" element="_YAo9QG1JEfGFvIBFhOqB5w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_YApkVW1JEfGFvIBFhOqB5w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_YApkVm1JEfGFvIBFhOqB5w" y="16"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YApkVG1JEfGFvIBFhOqB5w" x="574" y="107" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_2OHogG1JEfGFvIBFhOqB5w" type="3008" element="_2OHBcG1JEfGFvIBFhOqB5w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_2OHogm1JEfGFvIBFhOqB5w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_2OHog21JEfGFvIBFhOqB5w" x="-5" y="-59"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_2OHogW1JEfGFvIBFhOqB5w" x="831" y="98" width="42" height="42"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_F6T0nG1KEfGFvIBFhOqB5w" type="3005" element="_F6TNgG1KEfGFvIBFhOqB5w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_F6T0nm1KEfGFvIBFhOqB5w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_F6T0nW1KEfGFvIBFhOqB5w" x="1371" y="90" width="119" height="59"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_G7Wa3G1KEfGFvIBFhOqB5w" type="3005" element="_G7VzwG1KEfGFvIBFhOqB5w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_G7Wa3m1KEfGFvIBFhOqB5w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_G7Wa3W1KEfGFvIBFhOqB5w" x="782" y="211" width="142" height="70"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_dpjRFG1KEfGFvIBFhOqB5w" type="3008" element="_dpjREG1KEfGFvIBFhOqB5w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_dpj4IG1KEfGFvIBFhOqB5w" type="5026">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_dpj4IW1KEfGFvIBFhOqB5w" x="1" y="-63"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_dpjRFW1KEfGFvIBFhOqB5w" x="1140" y="98" width="43" height="43"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_1EvQgm1HEfGFvIBFhOqB5w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_1EvQg21HEfGFvIBFhOqB5w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_1EvQhG1HEfGFvIBFhOqB5w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_1Ev3km1HEfGFvIBFhOqB5w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_1EvQhW1HEfGFvIBFhOqB5w" x="48" y="500" width="2347" height="400"/>
        </children>
        <children xmi:type="notation:Node" xmi:id="_14IcUG1HEfGFvIBFhOqB5w" type="3007" element="_14H1QG1HEfGFvIBFhOqB5w">
          <children xmi:type="notation:DecorationNode" xmi:id="_14IcVW1HEfGFvIBFhOqB5w" type="5007"/>
          <children xmi:type="notation:DecorationNode" xmi:id="_14IcVm1HEfGFvIBFhOqB5w" type="7002">
            <children xmi:type="notation:Shape" xmi:id="_PjJXEG1KEfGFvIBFhOqB5w" type="3005" element="_PjIwAG1KEfGFvIBFhOqB5w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_PjJXEm1KEfGFvIBFhOqB5w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_PjJXEW1KEfGFvIBFhOqB5w" x="1095" y="56" width="119" height="59"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_UqrRnG1KEfGFvIBFhOqB5w" type="3005" element="_UqqqgG1KEfGFvIBFhOqB5w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_UqrRnm1KEfGFvIBFhOqB5w" type="5005"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_UqrRnW1KEfGFvIBFhOqB5w" x="1505" y="56" width="124" height="61"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_Vp8WOW1KEfGFvIBFhOqB5w" type="3027" element="_Vp8WMG1KEfGFvIBFhOqB5w" fontName="Segoe UI" fillColor="14334392" lineColor="10710316">
              <children xmi:type="notation:DecorationNode" xmi:id="_Vp8WO21KEfGFvIBFhOqB5w" type="5017"/>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_Vp8WOm1KEfGFvIBFhOqB5w" x="1733" y="56" width="120" height="60"/>
            </children>
            <children xmi:type="notation:Shape" xmi:id="_YCtkY21KEfGFvIBFhOqB5w" type="3003" element="_YCs9UG1KEfGFvIBFhOqB5w" fontName="Segoe UI">
              <children xmi:type="notation:DecorationNode" xmi:id="_YCtkZW1KEfGFvIBFhOqB5w" type="5025">
                <layoutConstraint xmi:type="notation:Location" xmi:id="_YCtkZm1KEfGFvIBFhOqB5w" y="5"/>
              </children>
              <layoutConstraint xmi:type="notation:Bounds" xmi:id="_YCtkZG1KEfGFvIBFhOqB5w" x="1980" y="72"/>
            </children>
          </children>
          <styles xmi:type="notation:DescriptionStyle" xmi:id="_14IcUW1HEfGFvIBFhOqB5w"/>
          <styles xmi:type="notation:FontStyle" xmi:id="_14IcUm1HEfGFvIBFhOqB5w" fontName="Segoe UI"/>
          <styles xmi:type="notation:LineStyle" xmi:id="_14IcU21HEfGFvIBFhOqB5w"/>
          <styles xmi:type="notation:FillStyle" xmi:id="_14IcV21HEfGFvIBFhOqB5w"/>
          <layoutConstraint xmi:type="notation:Bounds" xmi:id="_14IcVG1HEfGFvIBFhOqB5w" x="48" y="750" width="1297" height="250"/>
        </children>
      </children>
      <styles xmi:type="notation:DescriptionStyle" xmi:id="_nKx3WG1HEfGFvIBFhOqB5w"/>
      <styles xmi:type="notation:FontStyle" xmi:id="_nKx3WW1HEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <styles xmi:type="notation:LineStyle" xmi:id="_nKx3Wm1HEfGFvIBFhOqB5w"/>
      <styles xmi:type="notation:FillStyle" xmi:id="_nKx3W21HEfGFvIBFhOqB5w"/>
      <layoutConstraint xmi:type="notation:Bounds" xmi:id="_nKx3XG1HEfGFvIBFhOqB5w" width="2370" height="250"/>
    </children>
    <styles xmi:type="notation:DiagramStyle" xmi:id="_nKx3XW1HEfGFvIBFhOqB5w"/>
    <edges xmi:type="notation:Connector" xmi:id="_1CR8921IEfGFvIBFhOqB5w" type="4001" element="_1CR89G1IEfGFvIBFhOqB5w" source="_zLlhEG1IEfGFvIBFhOqB5w" target="_1nlpc21IEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_1CR8-m1IEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_1CR8-21IEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_1CR8-G1IEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_1CR8-W1IEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_6wn_021IEfGFvIBFhOqB5w" type="4001" element="_6wn_0G1IEfGFvIBFhOqB5w" source="_1nlpc21IEfGFvIBFhOqB5w" target="_1zJDh29IEfGjyPnck1rwvA" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_6wn_1m1IEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_6wn_121IEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_6wn_1G1IEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_6wn_1W1IEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_BwQEY21JEfGFvIBFhOqB5w" type="4001" element="_BwQEYG1JEfGFvIBFhOqB5w" source="_1nlpc21IEfGFvIBFhOqB5w" target="_Iu5RjW1JEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_BwQEZm1JEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_BwQEZ21JEfGFvIBFhOqB5w" x="-27" y="-17"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_BwQEZG1JEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_BwQEZW1JEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FJ3rk21JEfGFvIBFhOqB5w" type="4001" element="_FJ3rkG1JEfGFvIBFhOqB5w" source="_1zJDh29IEfGjyPnck1rwvA" target="_FJ3Eg21JEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FJ3rlm1JEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FJ3rl21JEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FJ3rlG1JEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FJ3rlW1JEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_XZh5821JEfGFvIBFhOqB5w" type="4001" element="_XZh58G1JEfGFvIBFhOqB5w" source="_Iu5RjW1JEfGFvIBFhOqB5w" target="_YApkU21JEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_XZh59m1JEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_XZh5921JEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_XZh59G1JEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_XZh59W1JEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_cQQ_Y21JEfGFvIBFhOqB5w" type="4001" element="_cQQ_YG1JEfGFvIBFhOqB5w" source="_YApkU21JEfGFvIBFhOqB5w" target="_56M2QHUsEfGKnvRhvJRGAg" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_cQQ_Zm1JEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_cQQ_Z21JEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_cQQ_ZG1JEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_cQQ_ZW1JEfGFvIBFhOqB5w" points="[0, -21, -333, 230]$[0, -89, -333, 162]$[333, -89, 0, 162]$[333, -222, 0, 29]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_i3fLB21JEfGFvIBFhOqB5w" type="4001" element="_i3fLBG1JEfGFvIBFhOqB5w" source="_56M2QHUsEfGKnvRhvJRGAg" target="_i3fLAG1JEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_i3fyEG1JEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_i3fyEW1JEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_i3fLCG1JEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_i3fLCW1JEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_15OWmm1JEfGFvIBFhOqB5w" type="4001" element="_15OWl21JEfGFvIBFhOqB5w" source="_YApkU21JEfGFvIBFhOqB5w" target="_2OHogG1JEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_15O9oG1JEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_15O9oW1JEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_15OWm21JEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_15OWnG1JEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_8Ydq421JEfGFvIBFhOqB5w" type="4001" element="_8Ydq4G1JEfGFvIBFhOqB5w" source="_2OHogG1JEfGFvIBFhOqB5w" target="_G7Wa3G1KEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_8Ydq5m1JEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_8Ydq521JEfGFvIBFhOqB5w" x="5" y="-16"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_8Ydq5G1JEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_8Ydq5W1JEfGFvIBFhOqB5w" points="[0, 22, -2, -135]$[0, 122, -2, -35]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_CvsSs21KEfGFvIBFhOqB5w" type="4001" element="_CvsSsG1KEfGFvIBFhOqB5w" source="_2OHogG1JEfGFvIBFhOqB5w" target="_dpjRFG1KEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_CvsStm1KEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_CvsSt21KEfGFvIBFhOqB5w" x="-16" y="-13"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_CvsStG1KEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_CvsStW1KEfGFvIBFhOqB5w" points="[20, -1, -289, -1]$[289, -1, -20, -1]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_FYFRRm1KEfGFvIBFhOqB5w" type="4001" element="_FYFRQ21KEfGFvIBFhOqB5w" source="_dpjRFG1KEfGFvIBFhOqB5w" target="_F6T0nG1KEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_FYFRSW1KEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_FYFRSm1KEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_FYFRR21KEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_FYFRSG1KEfGFvIBFhOqB5w" points="[22, 0, -183, 129]$[205, 0, 0, 129]$[205, -99, 0, 30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_NDa6YG1MEfGFvIBFhOqB5w" id="(0.7674418604651163,0.3953488372093023)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Jrsbhm1KEfGFvIBFhOqB5w" type="4001" element="_Jrsbg21KEfGFvIBFhOqB5w" source="_dpjRFG1KEfGFvIBFhOqB5w" target="_PjJXEG1KEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_JrsbiW1KEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Jrsbim1KEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Jrsbh21KEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_JrsbiG1KEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_To-kDm1KEfGFvIBFhOqB5w" type="4001" element="_To-kC21KEfGFvIBFhOqB5w" source="_PjJXEG1KEfGFvIBFhOqB5w" target="_UqrRnG1KEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_To_LEG1KEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_To_LEW1KEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_To-kD21KEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_To-kEG1KEfGFvIBFhOqB5w" points="[59, 1, -330, 160]$[392, 1, 3, 160]$[392, -130, 3, 29]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Vp89Qm1KEfGFvIBFhOqB5w" type="4001" element="_Vp8WPG1KEfGFvIBFhOqB5w" source="_UqrRnG1KEfGFvIBFhOqB5w" target="_Vp8WOW1KEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_Vp89RW1KEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Vp89Rm1KEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Vp89Q21KEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_Vp89RG1KEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_YCuLcG1KEfGFvIBFhOqB5w" type="4001" element="_YCtkZ21KEfGFvIBFhOqB5w" source="_Vp8WOW1KEfGFvIBFhOqB5w" target="_YCtkY21KEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_YCuLc21KEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_YCuLdG1KEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_YCuLcW1KEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_YCuLcm1KEfGFvIBFhOqB5w" points="[0, 0, 0, 0]$[0, 0, 0, 0]"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_RtSog21MEfGFvIBFhOqB5w" type="4001" element="_RtSogG1MEfGFvIBFhOqB5w" source="_G7Wa3G1KEfGFvIBFhOqB5w" target="_UqrRnG1KEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_RtTPkG1MEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_RtTPkW1MEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_RtSohG1MEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_RtSohW1MEfGFvIBFhOqB5w" points="[-71, 40, -714, -205]$[-71, 293, -714, 48]$[638, 293, -5, 48]$[638, 276, -5, 31]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_RtT2oG1MEfGFvIBFhOqB5w" id="(1.0,0.42857142857142855)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_Sdpucm1MEfGFvIBFhOqB5w" type="4001" element="_SdpHYG1MEfGFvIBFhOqB5w" source="_F6T0nG1KEfGFvIBFhOqB5w" target="_UqrRnG1KEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_SdpudW1MEfGFvIBFhOqB5w" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_Sdpudm1MEfGFvIBFhOqB5w" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_Sdpuc21MEfGFvIBFhOqB5w" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_SdpudG1MEfGFvIBFhOqB5w" points="[0, 0, -77, -371]$[123, 341, 46, -30]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_SdqVgG1MEfGFvIBFhOqB5w" id="(1.0,0.423728813559322)"/>
    </edges>
    <edges xmi:type="notation:Connector" xmi:id="_2zk0UG8dEfGgjsG-ztl8Nw" type="4001" element="_2zc4gG8dEfGgjsG-ztl8Nw" source="_nKx3T21HEfGFvIBFhOqB5w" target="_zLlhEG1IEfGFvIBFhOqB5w" roundedBendpointsRadius="10" routing="Rectilinear">
      <children xmi:type="notation:DecorationNode" xmi:id="_2zk0U28dEfGgjsG-ztl8Nw" type="6001">
        <layoutConstraint xmi:type="notation:Location" xmi:id="_2zk0VG8dEfGgjsG-ztl8Nw" y="-10"/>
      </children>
      <styles xmi:type="notation:FontStyle" xmi:id="_2zk0UW8dEfGgjsG-ztl8Nw" fontName="Segoe UI"/>
      <bendpoints xmi:type="notation:RelativeBendpoints" xmi:id="_2zk0Um8dEfGgjsG-ztl8Nw" points="[-2, -5, -171, -358]$[174, 316, 5, -37]"/>
      <sourceAnchor xmi:type="notation:IdentityAnchor" xmi:id="_2znQkG8dEfGgjsG-ztl8Nw" id="(0.9333333333333333,0.43333333333333335)"/>
    </edges>
  </notation:Diagram>
</xmi:XMI>
